### ISSUE TITLE
docker-compose不能开箱即用了

### ISSUE THREAD

**Issue by xie2673315720** [haxqer/confluence#15]
文件里用的mysql镜像好像需要修改两个地方
1.privileged: true 不添加这个mysql起不来，提示权限不够
2.启动后添加数据库，数据库初始化报错，看了一下提的问题，找到了个已经close的https://github.com/haxqer/confluence/issues/9#issue-1568278259
增加参数后就能启动了

另外 大佬有没有word excel txt 中文预览乱码的解决方法呢，看了一下官方的文档没搞太明白好像个个环境都不太一样

**Comment by haxqer** [comment]
可以开箱即用，用 root 即可
-
我没有在 confluence 中使用过 word excel ，我在使用中导出 pdf 时确实碰到了中文乱码问题。
需要导入 中文字体 才行。
另一个思路是，可以在插件市场中找找插件试试
