### ISSUE TITLE
关于中文乱码问题

### ISSUE THREAD

**Issue by sunny1025g** [haxqer/confluence#16]
您好，
首先感谢您辛苦制作镜像。
在使用您的制作的confluence过程中，添加代码的预览界面中文显示为框框
请您下次更新docker镜像的时候能不能安装中文字体包呢，谢谢
`apt install -y fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gkai00mp fonts-arphic-ukai fonts-arphic-uming`

**Comment by sunny1025g** [comment]
> done! https://github.com/haxqer/confluence/tree/latest-zh
> 
> 感谢~



> 谢谢，我另起一个分支



> 谢谢，我另起一个分支

再次感谢作者，zh分支已经安装测试，现在中文显示正常了
![20230426130929](https://user-images.githubusercontent.com/73953210/234475941-dee93cac-6dfc-4559-930a-bd61df8876df.png)

**Comment by sunny1025g** [comment]
已经测试最新的8.2.1和8.2.1-zh都正常使用，7.19.8-zh出现故障，无法进入配置界面，如下图所示
![20230426194805](https://user-images.githubusercontent.com/73953210/234565933-9e4866db-ff29-4844-9806-dcf6d2aa46ad.png)
7.19.8版本也无法进去自己安装字体包了，底层系统好像是使用的Debian9，是不是因为版本过低，有些源不支持了？不知道把底层更新到debian11是否正常，7.19.7一切正常哟

**Comment by haxqer** [comment]
感谢提醒，刚测试了下，确实有问题。

已经修复了，麻烦 `docker pull 7.19.8-zh` 试下

**Comment by haxqer** [comment]
8.2.2-zh 已更新

**Comment by sunny1025g** [comment]
> 7.19.8-zh
修复的7.19.8-zh，7.19.8和更新的8.2.2-zh，8.2.2四个版本都已经部署测试，目前使用正常，再次感谢

**Comment by haxqer** [comment]
最稳妥的方案: confluence 管理界面有备份功能，然后用 docker cp 把备份文件copy到宿主机, 例如 `docker cp confluence-srv:/var/confluence/temp/xmlexport-20230511-114410-73.zip xmlexport-20230511-114410-73.zip`.
新启动一台 confluence，初始化的时候选择从备份文件恢复，然后把 备份的zip文件上传上去就行了

其他方案(我没有尝试过):  选择同版本的 confluence, 直接替换即可

建议先尝试 最稳妥的方案， 直接替换compose可能有风险

**Comment by dreammis** [comment]
没听你的建议，结果崩了😂
原因是我是version 7.x->8.x，字符集有问题。
害得我挨个替换table， columns，database的字符集
如果是8，升级应该问题不大，低版本注意字符集设置
[How to Fix the Collation and Character Set of a MySQL Database manually](https://confluence.atlassian.com/kb/how-to-fix-the-collation-and-character-set-of-a-mysql-database-manually-744326173.html)

**Comment by haxqer** [comment]
有 7.x 的中文版，`7.19.8-zh`
@sunny1025g  已经测试过了
我忘记写在 Readme 文档里面了

**Comment by mocuishlelin** [comment]
https://blog.csdn.net/weixin_40647516/article/details/124632994
https://soulteary.com/2019/04/19/talk-about-confluence-with-docker.html
使用windows的字体也可以解决哈，适合本地安装或不想升级的伙伴们

**Comment by codermmd** [comment]
Ubuntu参考:把win中的字体cp到/usr/share/fonts, 然后volume添加`/usr/share/fonts:/usr/share/fonts`
