### ISSUE TITLE
添加宏之后，宏（Marco）标题中文出现"口口"乱码

### ISSUE THREAD

**Issue by UncleBigLu** [haxqer/confluence#17]
![image](https://user-images.githubusercontent.com/54833104/233824192-cde25ca8-4165-4d0f-aa41-db4a1d5d5e64.png)

**Comment by sunny1025g** [comment]
和上一个问题一样，你可以自己进入docker
执行以下命令安装中文字体包，然后重启docker就好了，不过我希望请作者下个版本更新时候集成字体
`apt update`
`apt install -y fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gkai00mp fonts-arphic-ukai fonts-arphic-uming`

**Comment by haxqer** [comment]
done!
https://github.com/haxqer/confluence/tree/latest-zh

感谢~
