### ISSUE TITLE
8.3.1不能用

### ISSUE THREAD

**Issue by lampda** [haxqer/confluence#22]
我的serverID：BPR7-3ERJ-J3HJ-J3W2

使用v8的脚本生成的license提示是invalid。请帮忙看看是什么原因，谢谢。

**Comment by haxqer** [comment]
我刚试了下，是可以的。我截图粘贴步骤，你看看你是哪里的步骤出了问题
![3513656100](https://github.com/haxqer/confluence/assets/25882796/d2f22676-56c1-4f30-80b7-da8edb640fa1)
![439206988](https://github.com/haxqer/confluence/assets/25882796/837eba19-930b-42c8-a1ed-243b540bddac)
![448216078](https://github.com/haxqer/confluence/assets/25882796/1d5a0dbb-af19-4b6f-b4f2-84d32e75cdfe)
![89857496](https://github.com/haxqer/confluence/assets/25882796/c6088001-6449-42c2-83a7-0513abb2c2ba)

**Comment by lampda** [comment]
好的,谢谢.目前没有问题了.
