### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by ronzhou18** [haxqer/confluence#3]
你好，大神，用你的镜像非常方便，不过现在有个问题没能解决，容器中的时区不能调整成上海，时间总是与实际时间差八小时，尝试挂载了宿主机的/etc/localtime也不能修改成功，请问有方法解决吗？

**Comment by ronzhou18** [comment]
解决了，这里正好记录下，也许其他同学也会遇到，是因为docker-compose.yml中TZ配置为Asia/Shanghai不能加单引号，去掉单引号就可以解决了，依然非常感谢大神镜像分享~~

**Comment by haxqer** [comment]
谢谢你~~
方便的话，可以提个 pr ?
