### ISSUE TITLE
Update image repository to 8.5.3

### ISSUE THREAD

**Issue by pldavid2** [haxqer/confluence#34]
@haxqer is it possible to update hub docker confluence image to 8.5.3? Seems previous ones have a severe security bug.

**Comment by haxqer** [comment]
忙成狗~~~
周末，我试试 8.5.3

**Comment by haxqer** [comment]
done~~

**Comment by 897896639** [comment]
8.5.2有漏洞，通过升级的方式升级到8.6.1，但许可证无效，然后我直接重新安装8.6.1，也显示许可证无效，8.6.1这个版本是还不支持pj吗？
![1](https://github.com/haxqer/confluence/assets/3367042/e378d672-82a4-410f-84de-69c49e95fc1b)

**Comment by haxqer** [comment]
加 `-d` 参数
这个参数的意思是生成 DataCenter 的证书

**Comment by 897896639** [comment]
感谢，加了-d 可以了
