### ISSUE TITLE
无法安装应用了

### ISSUE THREAD

**Issue by mMrBun** [haxqer/confluence#35]
当前版本haxqer/confluence:8.4.2-zh
Atlassian把应用商店关了，安装不了新的应用了
![image](https://github.com/haxqer/confluence/assets/52190211/a2db3b5e-47f0-45a8-be7a-131c26394239)

**Comment by haxqer** [comment]
证书换成 datacenter 
https://github.com/haxqer/confluence#datacenter-license

**Comment by mMrBun** [comment]
> 证书换成 datacenter https://github.com/haxqer/confluence#datacenter-license

ok,感谢，我一会试一下，我从下面这个网址找到了我的应用并上传也是可以用的
https://marketplace.atlassian.com/
