### ISSUE TITLE
从7升级到8，数据迁移问题

### ISSUE THREAD

**Issue by silkwormice** [haxqer/confluence#42]
从7升级到8，通过XML备份文件进行数据恢复，好像一直不成功，大家晓得原因不？

**Comment by youshaojun** [comment]
你可以把相关的报错截图发出来, 我之前也遇到过备份数据恢复不成功的问题, 我那个问题是由于备份数据里有重复数据导致的, 我将重复数据删除之后就正常了

**Comment by silkwormice** [comment]
> 你可以把相关的报错截图发出来, 我之前也遇到过备份数据恢复不成功的问题, 我那个问题是由于备份数据里有重复数据导致的, 我将重复数据删除之后就正常了

谢谢了，我这边跑了几遍流程，发现都是outofmemory错误，然后才发现是docker-compose配置的参数没生效，手动调整了 setenv.sh 的配置，就可以正常恢复了；后续验证数据，也没有再遇到其他数据丢失或者稀奇古怪的bug，还是很顺利的完成了验证，后续准备正式升级
