### ISSUE TITLE
install app on (plugin) jira

### ISSUE THREAD

**Issue by hacker-hackert** [haxqer/confluence#48]
hi haxqer
how can install or add an app on Jira like tempo and ...
I got this error:
![Screenshot 2024-01-06 at 8 32 30 am](https://github.com/haxqer/confluence/assets/121010379/2d74e886-14a3-4534-a820-ec4626163b80)
also, I tried to add apps from Upload app button but i got this error:
![Screenshot 2024-01-06 at 8 44 06 am](https://github.com/haxqer/confluence/assets/121010379/a5b34c7e-a913-4f70-a643-e2f18c88ba39)

**Comment by haxqer** [comment]
Using the datacenter license

**Comment by abbas-raadco** [comment]
hi haxqer
thanks for your response
how can I use the datacenter license?
I run Jira on my server with this command:
`docker volume create jira_home_data && docker network create jira-network && docker run -p 8080:8080 -v jira_home_data:/var/jira --network jira-network --name jira-srv -e TZ='Asia/Shanghai' haxqer/jira:9.12.1`

and for a license I used this command:
`docker exec jira-srv java -jar /var/agent/atlassian-agent.jar \
    -d \
    -p jira \
    -m Hello@world.com \
    -n Hello@world.com \
    -o your-org \
    -s you-server-id-xxxx`
    
    now how can I got a datacenter license ?

**Comment by haxqer** [comment]
`-d` to generate the datacenter license
https://github.com/haxqer/confluence?tab=readme-ov-file#how-to-hack-confluence

```
docker exec confluence-srv java -jar /var/agent/atlassian-agent.jar \
    -d \
    -p conf \
    -m Hello@world.com \
    -n Hello@world.com \
    -o your-org \
    -s you-server-id-xxxx
```

**Comment by haxqer** [comment]
1. Generate a datacenter license for Jira: https://github.com/haxqer/jira?tab=readme -Ov file # how to hack jira
2. Modify Jira's license: Administration -> Applications -> Version&licenses
3. Generate license for jira plugin: https://github.com/haxqer/jira?tab=readme -Ov file # how to hack jira plugin
4. Paste the license of the Jira plugin

**Comment by hacker-hackert** [comment]
Thanks for your suport
My issue resolved
