### ISSUE TITLE
I have trouble with upgrade to the new version

### ISSUE THREAD

**Issue by muratovuz** [haxqer/confluence#49]
Hi! I can't use my confluence after upgrading to the 8.6.1 or latest version. I'm getting error Incompatible License.
Previous versions working well. Thank's an advance.

<img width="1450" alt="image" src="https://github.com/haxqer/confluence/assets/74892243/5bbe8e6d-9550-4e77-9427-077909b8c156">

**Comment by haxqer** [comment]
The new version can only use the datacenter license:
```
docker exec confluence-srv java -jar /var/agent/atlassian-agent.jar \
    -d \
    -p conf \
    -m Hello@world.com \
    -n Hello@world.com \
    -o your-org \
    -s you-server-id-xxxx
```
