### ISSUE TITLE
每次通过docker-compose重启后都需要重新破解

### ISSUE THREAD

**Issue by CatsMyLove** [haxqer/confluence#59]
你好请问 我每次通过docker-compose down  然后再docker-compose up -d 启动后，都需要重新破解，并且破解后继续使用原来的数据库提示需要覆盖数据库而不能继续使用。这个有办法解决吗。通过docker restart 就不用重新破解。

**Comment by haxqer** [comment]
你自己改过 docker-compose.yaml 吗?

**Comment by CatsMyLove** [comment]
我的问题，我再这个配置里面加了 window字体链接。第一次启动的时候会重新破解
