### ISSUE TITLE
Removed axlroden/confluence

### ISSUE THREAD

**Issue by n0a** [haxqer/confluence#6]
Pulling confluence (axlroden/confluence:)...
**ERROR:** The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Can you fix this for new container? Thx.

**Comment by axlroden** [comment]
told him not to merge my repo, the docker image is not built.. use previous versions or find the agent yourself.

**Comment by haxqer** [comment]
Fixed.
I'm sorry.
I will update this project next weekend.

**Comment by haxqer** [comment]
update to 7.19.0

https://github.com/haxqer/confluence/blob/master/Dockerfile
