### ISSUE TITLE
confluence加载很慢

### ISSUE THREAD

**Issue by Giftedcat** [haxqer/confluence#60]
首先，感谢作者无私的共享，为社区提供的服务

**硬件配置**我目前租赁了一台2核8G的服务器，跑了一个confluence作为内部wiki使用
之前是5的版本，现在升级到8
**现象**：加载比较卡顿，首页打开后静态页面是正常加载的，比较快，但是中间的列表加载很缓慢
包括打开空间也是加载比较缓慢，目录也比较缓慢

**我做了哪些优化**  我调整了jvm的大小为2gb，可以在系统中查看到，但是并没有特别大的效果

**希望得到的帮助**   想问一下是不是cpu性能太差了，还是我哪里配置的有问题导致这个情况

**Comment by haxqer** [comment]
租的服务器带宽是多少呢？
可以尝试下 重建索引？

如果是内部用，如果人不多建议买一台小型的主机放在公司内部；如果人多买台服务器。现在硬件价格都很低了。
我自己家里用的是一台 M73(早些年折腾黑苹果淘汰下来的，16GB内存 1TB 存储 总价不超过800)，跑的 jira+confluence 已经稳定运行2年了。公司用的是一台服务器，淘宝买的二手的服务器(128GB内存 40TB 存储 总价不超过 5000)。

**Comment by Giftedcat** [comment]
感谢解答

服务器带宽是5M
主要为了方便公司内外使用都方便，所以就租了台小水管的云服务器，后续倒是可以考虑内网穿透的方案

我重新构建了索引后确实速度快了一些了，但是与我们之前部署的5版本的速度还是有点差距
不过之前版本5的confluence有漏洞被人攻击力，所以才想着升级到8
