### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by mfide** [haxqer/confluence#66]
Hello,

When I try to `docker compose up -d` on my `RaspberryPi5 8GB`, I get following error:

`confluence The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Is it possible to add `ARM64` support?

Thanks.

**Comment by haxqer** [comment]
Compilation has been completed; please utilize version `8.9.4`. 
Should any issues arise during use, do not hesitate to report them, and I will endeavor to address them to the best of my ability.

**Comment by mfide** [comment]
`image: haxqer/confluence:8.9.4-arm` worked fine, thank you :)
