### ISSUE TITLE
大神你好，怎么配置自己的数据库mysql8.0

### ISSUE THREAD

**Issue by sunson468** [haxqer/confluence#7]
是安装好之后有了配置文件再自己设置吗？

**Comment by haxqer** [comment]
https://github.com/haxqer/confluence/blob/master/Dockerfile#L9

这行代码，替换 mysql 的 driver version
然后 docker build 成你的镜像即可

**Comment by haxqer** [comment]
https://github.com/haxqer/confluence
https://github.com/haxqer/jira/blob/rm/README_zh.md
---
都已经支持 mysql8.0

**Comment by d1m0nstr** [comment]
hello friend - what about confluence 8.0.0? 
and thank you very match for your repo - it's help us)

**Comment by haxqer** [comment]
@d1m0nstr 

https://github.com/haxqer/confluence/tree/8.0.0

This version is not fully tested, please use it with caution.

**Comment by d1m0nstr** [comment]
thank you very match - we'll test it

**Comment by d1m0nstr** [comment]
after 5 days of test - it's version faster about 30% than 7.19.x
but it has little problem with cookie - every day you need to login. (atlassian fixed it in 8.0.1)
we happy to use this version. thank you [haxqer](https://github.com/haxqer)
