### ISSUE TITLE
SSL and HTTPS

### ISSUE THREAD

**Issue by Vecel4akA** [haxqer/confluence#74]
How to enable HTTPS for confluence using docker container? Pls help with this problem, cant search any method anywhere

**Comment by haxqer** [comment]
https://confluence.atlassian.com/doc/running-confluence-over-ssl-or-https-161203.html

**Comment by Vecel4akA** [comment]
ty, one more question - Where is location WEB-INF/web.xml file? On the server(docker) or on the container with confluence? Cant search this

**Comment by Vecel4akA** [comment]
![image](https://github.com/user-attachments/assets/44df988f-4f9c-4560-97d6-62b3913663dd)

**Comment by Vecel4akA** [comment]
Ty so much, one more question
Default port 8090 for confluence container. Need I change this port in docker-compose.yml after enable 8443 HTTPS redirection? i was edit my container with this instructions, but my site dont work on 8443 port. Help pls
